### ISSUE TITLE
Target [Psr\Http\Client\ClientInterface] is not instantiable.

### ISSUE THREAD

**Issue by johnRivs** [hannesvdvreken/guzzle-debugbar#12]
I'm using Laravel 8, `barryvdh/laravel-debugbar:^3.5` and `hannesvdvreken/guzzle-debugbar:^3.0`.

```php
use GuzzleHttp\ClientInterface;

Route::get('/', function () {
    $http = app(ClientInterface::class);

    $http->get('https://httpbin.org/get');
});
```

Commenting out [this line](https://github.com/hannesvdvreken/guzzle-debugbar/blob/3.x/src/Support/Laravel/ServiceProvider.php#L43) gets rid of the problem.
`^2.0` works fine though.

**Comment by hannesvdvreken** [comment]
Your problem should be fixed in https://github.com/hannesvdvreken/guzzle-debugbar/releases/tag/3.0.1.

```sh
composer update hannesvdvreken/guzzle-debugbar:^3.0.1
```

Please consider donating to https://github.com/sponsors/hannesvdvreken for continued support.
