### ISSUE TITLE
Is there any way to log POST and PUT parameters

### ISSUE THREAD

**Issue by AhmadOf** [hannesvdvreken/guzzle-debugbar#13]
I am trying to use this package to track http request happening in laravel using guzzle and I managed to do that but I still can't see POST and PUT params, and just can see GET params, so is there anyway to see those params.

thank you

**Comment by hannesvdvreken** [comment]
Hi. POST and PUT params can be of a lot of different kinds and formats.

It's best to write your own [Guzzle Middleware](https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#middleware) to add to the stack. 

See [here](https://github.com/hannesvdvreken/guzzle-debugbar/blob/3.x/src/Support/Laravel/ServiceProvider.php#L61) how Guzzle profiling middleware are added to the stack

**Comment by hannesvdvreken** [comment]
If this package helps you, please consider [donating](https://github.com/sponsors/hannesvdvreken).
