### ISSUE TITLE
Example of how to use it with Laravel Http Client

### ISSUE THREAD

**Issue by salarmehr** [hannesvdvreken/guzzle-debugbar#15]
Thanks for this library, could you possibly add an example of how to use this with the Laravel HTTP client, which is built on top of Guzzle? I guess https://laravel.com/docs/10.x/http-client#global-middleware should be used, But not clear to me how.

**Comment by hannesvdvreken** [comment]
It's reaaaally easy though. If you'd have searched for the `globalRequestMiddleware` method (which is just a simplified type of middleware), you would have found out there's also a `globalMiddleware` method.

https://laravel.com/api/10.x/Illuminate/Http/Client/Factory.html#method_globalMiddleware

```php
$debugBar = app('debugbar');

// Get data collector.
$timeline = $debugBar->getCollector('time');

// Wrap the timeline.
$profiler = new \GuzzleHttp\Profiling\Debugbar\Profiler($timeline);

// Add the middleware to the global http client middleware stack
Http::globalMiddleware(new \GuzzleHttp\Profiling\Middleware($profiler));

// PSR-3 logger:
$logger = $debugBar->getCollector('messages');

// Create a new Log middleware.
Http::globalMiddleware(\GuzzleHttp\Middleware::log($logger, new \GuzzleHttp\MessageFormatter()));
```

And that's it.

**Comment by aiden-adrian-ext-gtg** [comment]
@hannesvdvreken thanks, where this snippet of code is supposed to be placed? 
Putting it on in the AppServiceProvider doesn't work and it complains about `time` collector missing, while that is enabled. 

I hoped using this repo be as easy as adding/enabling a collector to config/debugbar.php `'collectors'` array.

**Comment by salarmehr** [comment]
@hannesvdvreken where this snipper is supposed to be placed?
I hoped registering the service provider to be enough to kick start using this extension or adding it to the debugebar config file.

**Comment by hannesvdvreken** [comment]
My friend.

https://laravel.com/docs/10.x/providers#writing-service-providers

One of the required skills of a software developer is to find solutions by reading code and reading documentation. I recommend spending some time developing this skill.

**Comment by salarmehr** [comment]
@hannesvdvreken you don't have to be rude and unhelpful. A basic human skill is to treat others respectfully. Your package has a service provided and you failed to put the basic code to make it useable there. Your behaviour is repulsive.

**Comment by hannesvdvreken** [comment]
Oh, I was being helpful. I gave you a link and advice.
