### ISSUE TITLE
Add to package that makes guzzle calls

### ISSUE THREAD

**Issue by lukasoppermann** [hannesvdvreken/guzzle-debugbar#4]
Hey, 

I am trying to add this to a package that makes guzzle calls, so if the debugbar exists, it will write guzzle calls to it.

My Setup:
- Laravel app with debug bar installed via https://github.com/barryvdh/laravel-debugbar
- Package with guzzle, that is required via composer and autoloaded via PSR

I figured I just do something like this in the main file of the package.

```php
public function newClient($opts = [], $debugBar = NULL)
    {
        $handler = [];
        if(is_a($debugBar, '\DebugBar\StandardDebugBar')){
            $debugBar = $debugBar;
            // Get data collector.
            $timeline = $debugBar->getCollector('time');
            // Wrap the timeline.
            $profiler = new GuzzleHttp\Profiling\Debugbar\Profiler($timeline);
            \Log::debug(json_encode($profiler));
            // Add the middleware to the stack
            $stack = GuzzleHttp\HandlerStack::create();
            $stack->unshift(new GuzzleHttp\Profiling\Middleware($profiler));

            $handler = ['handler' => $stack];
        }
        // New up the client with this handler stack.
        return new GuzzleHttp\Client(array_merge(
            $handler,
            $opts
        ));
    }
```

However, I do not see the guzzle calls in the debugbar show up. It still just shows Booting and application. Can you tell me what I am doing wrong.

**Comment by hannesvdvreken** [comment]
At first sight, this looks correct. Have you tried using a step debugger to inspect what lines of code are being run?

**Comment by lukasoppermann** [comment]
Ahh, no, where would I use it, in the package or in the app?

**Comment by hannesvdvreken** [comment]
Right where you've put these lines of code, that you posted above. ;-)

**Comment by lukasoppermann** [comment]
Okay, I will try this. I am just thinking, do I have to supply the debugbar as a parameter? Because I am not sure I am doing it correctly.

**Comment by lukasoppermann** [comment]
Okay, it was all correct, I just called the package twice and only added the instance of debugbar to the call I did not actually use on the pages I tested it on. :( Sorry, but thanks for the quick response.
