### ISSUE TITLE
Unable to log request in timeline

### ISSUE THREAD

**Issue by rajma996** [hannesvdvreken/guzzle-debugbar#6]
Hello ,

  I've been trying to use guzzle-debugbar, and followed steps at [Readme](https://github.com/hannesvdvreken/guzzle-debugbar/blob/master/README.md) . Though I am not getting any errors, requests aren't getting logged in the timeline .

Here is  the controller I am using  in laravel, I've used [laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) to integrate php-debugbar with laravel 

`
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use GuzzleHttp\Profiling\Debugbar\Profiler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Profiling\Middleware;
`

class testphpcontroller3 extends Controller
{

    public function index(Request $request)
    {

        $debugBar = new \DebugBar\StandardDebugBar();

        $timeline = $debugBar->getCollector('time');

        $profiler = new Profiler($timeline);

        $stack = HandlerStack::create();
        $stack->unshift(new Middleware($profiler));

        \Debugbar::info($stack);

        $client = new \GuzzleHttp\Client(['handler' => $stack]);

        \Debugbar::info($client);

        \Debugbar::error("test error");

        $client->get("https://www.google.com");
    }
} `

And I get the response :
![resp1](https://user-images.githubusercontent.com/9934336/27581143-7c94cd92-5b4a-11e7-8e7a-3a770075baa7.png) 
![resp2](https://user-images.githubusercontent.com/9934336/27581153-84ed30a6-5b4a-11e7-9b27-38d1e176a4d9.png)

Request however aren't logged

**Comment by hannesvdvreken** [comment]
You seem to initiate a new debugbar. You should try getting the one configured by the laravel-debugbar from the ioc container.

```
$debugbar = App::make('debugbar');

// instead of
$debugBar = new \DebugBar\StandardDebugBar();
```

Let me know if it worked.

**Comment by rajma996** [comment]
@hannesvdvreken  yeah that was the error .
Thanks a lot .
