### ISSUE TITLE
'time' is not a registered collector

### ISSUE THREAD

**Issue by scheMeZa** [hannesvdvreken/guzzle-debugbar#7]
**Before explaining the problem, yes, ```time``` and ```exceptions``` is set to true in ```config/debugbar.php```'s collectors array.**

The package works great when loading the webpage ```project.dev```, the timings of guzzle requests is in my Debugbar as expected. Works great on the webpage, thank you.

The problem is when I try to run any ```php artisan``` command in the console, it then throws:
```[DebugBar\DebugBarException] 'time' is not a registered collector```

I can confirm that ```time``` **is** a registered collector by making a quick route in ```web.php```:
```php
Route::get('/collectors', function () {
    $debugbar = resolve('debugbar');
    dd($debugbar->getCollectors());
});
```

This results in:
![image](https://user-images.githubusercontent.com/7773361/33422687-2c1a928a-d5bf-11e7-9e11-b1584148c389.png)

I can use ```php artisan``` commands when I take your service provider out of my ```config/app.php```.

Hope I gave you enough information.

**Comment by hannesvdvreken** [comment]
Can you do

```php
$debugbar = resolve('debugbar');
dd($debugbar->getCollectors());
```
in an Artisan command?

Debugbar is something that's only being rendered as a script in the bottom of an HTML page. So I suspect that debugbar is not completely configured when PHP is run in CLI.

**Comment by hannesvdvreken** [comment]
Looks like you'll need to check with laravel-debugbar why that is. Good luck, and cheers!

**Comment by barryvdh** [comment]
Debugbar isn't enabled on the CLI, because it usually creates a lot of slowdown and isn't used (eg. updating a lot of data etc) You could enable it manually probably.

**Comment by eznix86** [comment]
This is interfering with `queue:work` any way to fix it ?

Currently I use guzzle with SaloonPHP, which is being used during a job
